logging:
  level:
    root: info
    top.jasminecloud: debug
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  zipkin:
    service:
      name: zipkin-server
zuul:
  ignoredPatterns: /favicon.ico
  sendErrorFilter: 
    post: 
      display: true
  SendResponseFilter:
    post:
      display: true
  servlet-path: /
  sensitiveHeaders: 
  routes:
    appblog: /appblog-api/**
    zuul-server: /zuul-server-api/**
hystrix:    
  command:   
    default: 
      execution:
        timeout:
          enabled: true 
        isolation: 
          thread: 
            timeoutInMilliseconds: 80000
ribbon: 
  ReadTimeout: 20000
  ConnectTimeout: 20000
